sequential: false
variables:
  system: ['aurora']
  partition: ['']
  # protocol: ['Simple']
  fsdp_batch_size: [16]
  sharding_factor: [8]
  num_units: [16]
  # algorithm: ['ring', 'tree']
  # n_channels: [2, 4, 8, 16, 32]
  # n_threads: [64, 128, 256, 512]
  nodes: [2, 4, 8, 16, 32, 64, 128]
  fsdp_model: ['llama3-8b', 'minerva-7b']
jobs:
  - config: "{system}__algo_{algorithm}__{protocol}_protocol__{nodes}_nodes"
    config_jobs:
      - tag: "fsdp_{fsdp_model}_{algorithm}"
        command: "srun -N {nodes} ./cpp/data_parallel/fsdp {fsdp_model} {num_units} {sharding_factor} . -w 1 -r 3 -b {fsdp_batch_size} -g INTEL1550"
  - config: "{system}__channels{n_channels}__threads{n_threads}__{nodes}nodes"
    config_jobs:
      - tag: "fsdp_{fsdp_model}_ch{n_channels}_th{n_threads}"
        command: "srun -N {nodes} ./cpp/data_parallel/fsdp {fsdp_model} {num_units} {sharding_factor} . -w 1 -r 3 -b {fsdp_batch_size} -g INTEL1550"
  - config: "{system}__oneccl__default__{nodes}_nodes"
    config_jobs:
      - tag: "fsdp_{fsdp_model}_oneccl_default_{nodes}_nodes"
        command: "srun -N {nodes} ./cpp/data_parallel/fsdp {fsdp_model} {num_units} {sharding_factor} . -w 1 -r 3 -b {fsdp_batch_size} -g INTEL1550"